/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Helpers.TelaInicialHelper;
import Controller.TelaInicialController;
import Model.Dao.MusicaDAO;
import com.sun.prism.paint.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javazoom.jl.decoder.JavaLayerException;

/**
 *
 * @author Samuel
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    
   // private final ImageIcon fundoCell;
    
        private final TelaInicialController controller;
        private final MusicaDAO dao;
    
    public TelaInicial() throws FileNotFoundException, JavaLayerException {
      
        initComponents();
        
        setResizable(false);
        setSize(jLabelFundoColorido.getWidth() , jLabelFundoColorido.getHeight()+30);
        setLocationRelativeTo(null);
        jButtonPlay.setBackground(java.awt.Color.white);
        /* try {
        
        UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        Logger.getLogger(TelaInicialHelper.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        controller = new TelaInicialController(this);
        dao = new MusicaDAO(controller.getModel());
         
        
        controller.criarDiretorio();
        controller.iniciar();
        
        
        /* fundoCell = new ImageIcon("Source Packages/View.Images/Ouvindo_Musica_gif.gif");
        fundoCell.setImage(fundoCell.getImage().getScaledInstance(jLabelFundoCelular.WIDTH, jLabelFundoCelular.HEIGHT, 1));
        jLabelFundoCelular.setIcon(fundoCell);*/
    
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxMusicas = new javax.swing.JComboBox<>();
        jProgressBarVideoTempo = new javax.swing.JProgressBar();
        jLabelTempoMusica = new javax.swing.JLabel();
        jLabelMp3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelDownload = new javax.swing.JLabel();
        jLabelAddMusic = new javax.swing.JLabel();
        jButtonAddMusic = new javax.swing.JButton();
        jButtonDownload = new javax.swing.JButton();
        jButtonYoutube = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jLabelMusicaA1 = new javax.swing.JLabel();
        jLabelMusicaA = new javax.swing.JLabel();
        jLabelMusicaAtual = new javax.swing.JLabel();
        jLabelTelaIpod = new javax.swing.JLabel();
        jLabelFundoCelular = new javax.swing.JLabel();
        jLabelFundoColorido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(464, 625));
        getContentPane().setLayout(null);

        jComboBoxMusicas.setBackground(new java.awt.Color(153, 0, 255));
        jComboBoxMusicas.setForeground(new java.awt.Color(0, 255, 0));
        jComboBoxMusicas.setMaximumRowCount(5);
        getContentPane().add(jComboBoxMusicas);
        jComboBoxMusicas.setBounds(60, 240, 250, 26);

        jProgressBarVideoTempo.setBackground(new java.awt.Color(255, 0, 0));
        jProgressBarVideoTempo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jProgressBarVideoTempo.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBarVideoTempo.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jProgressBarVideoTempo.setStringPainted(true);
        getContentPane().add(jProgressBarVideoTempo);
        jProgressBarVideoTempo.setBounds(60, 310, 210, 20);

        jLabelTempoMusica.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelTempoMusica.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTempoMusica.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/Disco 1.png")));
        jLabelTempoMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabelTempoMusica);
        jLabelTempoMusica.setBounds(60, 270, 200, 50);

        jLabelMp3.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/mp3_32px.png")));
        getContentPane().add(jLabelMp3);
        jLabelMp3.setBounds(270, 330, 0, 0);

        jButton1.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/Pause_32px_2.png")));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 280, 40, 40);

        jLabelDownload.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabelDownload.setForeground(new java.awt.Color(153, 0, 204));
        jLabelDownload.setText("Download");
        getContentPane().add(jLabelDownload);
        jLabelDownload.setBounds(70, 470, 64, 15);

        jLabelAddMusic.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabelAddMusic.setForeground(new java.awt.Color(0, 255, 51));
        jLabelAddMusic.setText("Adicionar Musica");
        getContentPane().add(jLabelAddMusic);
        jLabelAddMusic.setBounds(110, 340, 149, 22);

        jButtonAddMusic.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jButtonAddMusic.setForeground(new java.awt.Color(51, 204, 0));
        jButtonAddMusic.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/Add_32px.png")));
        jButtonAddMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jButtonAddMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMusicActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddMusic);
        jButtonAddMusic.setBounds(60, 330, 40, 40);

        jButtonDownload.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/Dowload_Icon.png")));
        jButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDownload);
        jButtonDownload.setBounds(70, 420, 60, 40);

        jButtonYoutube.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/youtube_Logo_32px.png")));
        jButtonYoutube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYoutubeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonYoutube);
        jButtonYoutube.setBounds(260, 430, 40, 30);

        jButtonPlay.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPlay.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPlay.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/Play_Blue_32px.png")));
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlay);
        jButtonPlay.setBounds(160, 430, 50, 40);

        jLabelMusicaA1.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabelMusicaA1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMusicaA1.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/musical-note.png")));
        jLabelMusicaA1.setText("Escolha uma musica:");
        getContentPane().add(jLabelMusicaA1);
        jLabelMusicaA1.setBounds(60, 200, 250, 40);
        //jLabelMusicaA1.setBounds(60, 200, 250, );

        jLabelMusicaA.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabelMusicaA.setForeground(new java.awt.Color(153, 0, 204));
        jLabelMusicaA.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/Equalizador(1)_32px.png")));
        //nomedalabel.setIcon(new ImageIcon(Nomedaclassequevailevarimagem.class.getResource("caminho/caminho/imagem.gif")));
        jLabelMusicaA.setText("Musica Atual:");
        jLabelMusicaA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelMusicaA);
        jLabelMusicaA.setBounds(60, 130, 250, 30);

        jLabelMusicaAtual.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabelMusicaAtual.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabelMusicaAtual);
        jLabelMusicaAtual.setBounds(60, 160, 250, 30);
        //jLabelMusicaAtual.setBounds(60, 170, 250, );

        jLabelTelaIpod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Ipod_TelaInicial.png"))); // NOI18N
        getContentPane().add(jLabelTelaIpod);
        jLabelTelaIpod.setBounds(-70, 0, 450, 530);

        jLabelFundoCelular.setIcon(new ImageIcon(TelaInicial.class.getResource("/View/Images/Ouvindo_Musica_gif.gif")));
        //jLabelFundoCelular.setIcon(new ImageIcon(TelaInicial.class.getResource() ));

        //nomedalabel.setIcon(new ImageIcon(Nomedaclassequevailevarimagem.class.getResource("caminho/caminho/imagem.gif")));
        getContentPane().add(jLabelFundoCelular);
        jLabelFundoCelular.setBounds(40, 100, 290, 300);

        jLabelFundoColorido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/fundo-colorido-TelaInicial.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoColorido);
        jLabelFundoColorido.setBounds(0, 0, 380, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonYoutubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYoutubeActionPerformed
        
        controller.acessarYouTube();
        
    }//GEN-LAST:event_jButtonYoutubeActionPerformed

    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadActionPerformed

        controller.acessarDownload();

    }//GEN-LAST:event_jButtonDownloadActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed

        controller.TocarSelectedMusica();
       
        
        
        
        
        
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonAddMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMusicActionPerformed
       
        
        controller.addMusica();
        
        
    }//GEN-LAST:event_jButtonAddMusicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        controller.pauser();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    
                    new TelaInicial().setVisible(true);
                    
                } catch (FileNotFoundException | JavaLayerException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddMusic;
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonYoutube;
    private javax.swing.JComboBox<Object> jComboBoxMusicas;
    private javax.swing.JLabel jLabelAddMusic;
    private javax.swing.JLabel jLabelDownload;
    private javax.swing.JLabel jLabelFundoCelular;
    private javax.swing.JLabel jLabelFundoColorido;
    private javax.swing.JLabel jLabelMp3;
    private javax.swing.JLabel jLabelMusicaA;
    private javax.swing.JLabel jLabelMusicaA1;
    private javax.swing.JLabel jLabelMusicaAtual;
    private javax.swing.JLabel jLabelTelaIpod;
    private javax.swing.JLabel jLabelTempoMusica;
    private javax.swing.JProgressBar jProgressBarVideoTempo;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonAddMusic() {
        return jButtonAddMusic;
    }

    public void setjButtonAddMusic(JButton jButtonAddMusic) {
        this.jButtonAddMusic = jButtonAddMusic;
    }

    public JButton getjButtonDownload() {
        return jButtonDownload;
    }

    public void setjButtonDownload(JButton jButtonDownload) {
        this.jButtonDownload = jButtonDownload;
    }

    public JButton getjButtonPlay() {
        return jButtonPlay;
    }

    public void setjButtonPlay(JButton jButtonPlay) {
        this.jButtonPlay = jButtonPlay;
    }

    public JButton getjButtonYoutube() {
        return jButtonYoutube;
    }

    public void setjButtonYoutube(JButton jButtonYoutube) {
        this.jButtonYoutube = jButtonYoutube;
    }

    public JComboBox<Object> getjComboBoxMusicas() {
        return jComboBoxMusicas;
    }

    public void setjComboBoxMusicas(JComboBox<Object> jComboBoxMusicas) {
        this.jComboBoxMusicas = jComboBoxMusicas;
    }

    public JLabel getjLabelAddMusic() {
        return jLabelAddMusic;
    }

    public void setjLabelAddMusic(JLabel jLabelAddMusic) {
        this.jLabelAddMusic = jLabelAddMusic;
    }

    public JLabel getjLabelDownload() {
        return jLabelDownload;
    }

    public void setjLabelDownload(JLabel jLabelDownload) {
        this.jLabelDownload = jLabelDownload;
    }

    public JLabel getjLabelFundoCelular() {
        return jLabelFundoCelular;
    }

    public void setjLabelFundoCelular(JLabel jLabelFundoCelular) {
        this.jLabelFundoCelular = jLabelFundoCelular;
    }

    public JLabel getjLabelFundoColorido() {
        return jLabelFundoColorido;
    }

    public void setjLabelFundoColorido(JLabel jLabelFundoColorido) {
        this.jLabelFundoColorido = jLabelFundoColorido;
    }

    public JLabel getjLabelMp3() {
        return jLabelMp3;
    }

    public void setjLabelMp3(JLabel jLabelMp3) {
        this.jLabelMp3 = jLabelMp3;
    }

    public JLabel getjLabelMusicaA() {
        return jLabelMusicaA;
    }

    public void setjLabelMusicaA(JLabel jLabelMusicaA) {
        this.jLabelMusicaA = jLabelMusicaA;
    }

    public JLabel getjLabelMusicaA1() {
        return jLabelMusicaA1;
    }

    public void setjLabelMusicaA1(JLabel jLabelMusicaA1) {
        this.jLabelMusicaA1 = jLabelMusicaA1;
    }

    public JLabel getjLabelMusicaAtual() {
        return jLabelMusicaAtual;
    }

    public void setjLabelMusicaAtual(JLabel jLabelMusicaAtual) {
        this.jLabelMusicaAtual = jLabelMusicaAtual;
    }

    public JLabel getjLabelTelaIpod() {
        return jLabelTelaIpod;
    }

    public void setjLabelTelaIpod(JLabel jLabelTelaIpod) {
        this.jLabelTelaIpod = jLabelTelaIpod;
    }

    public JLabel getjLabelTempoMusica() {
        return jLabelTempoMusica;
    }

    public void setjLabelTempoMusica(JLabel jLabelTempoMusica) {
        this.jLabelTempoMusica = jLabelTempoMusica;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JProgressBar getjProgressBarVideoTempo() {
        return jProgressBarVideoTempo;
    }

    public void setjProgressBarVideoTempo(JProgressBar jProgressBarVideoTempo) {
        this.jProgressBarVideoTempo = jProgressBarVideoTempo;
    }

    
    

}
